// Generate a self-contained illustrated HTML manual from a tour + the
// screenshots captured by the Playwright run. One manual per language
// present in the export's i18n maps; screenshots are shared across
// languages.
//
// The manual embeds every screenshot as a base64 data: URI so the file is
// fully self-contained — open it in a browser, select all, and paste
// directly into Odoo Knowledge (or any rich-text editor); the images travel
// with the paste instead of depending on relative file paths surviving it.
import fs from "node:fs";
import path from "node:path";
import { tr } from "./loadTours.mjs";
import { shotFile, shotDir } from "./names.mjs";

const LANG_NAMES = {
  en_US: "English",
  si_LK: "සිංහල (Sinhala)",
  ta_IN: "தமிழ் (Tamil)",
};

// Human-readable hint per validation type, for the manual.
const VALIDATION_HINT = {
  required: "This field is required.",
  integer: "Enter a whole number.",
  float: "Enter a number (decimals allowed).",
  email: "Enter a valid email address.",
  phone: "Enter a valid phone number.",
  url: "Enter a valid URL.",
  date: "Enter a valid date.",
  alpha: "Letters only.",
  alphanumeric: "Letters and numbers only.",
  regex: "Enter a value in the expected format.",
};

function langName(code) {
  return LANG_NAMES[code] || code;
}

function escapeHtml(s) {
  return String(s == null ? "" : s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Read a screenshot PNG and return it as a base64 data: URI, or null. */
function embedImage(absPath) {
  if (!fs.existsSync(absPath)) return null;
  const buf = fs.readFileSync(absPath);
  return `data:image/png;base64,${buf.toString("base64")}`;
}

function genHtml(tour, lang, total) {
  const dir = shotDir(tour.slug);
  const title = tr(tour.name, tour.name_i18n, lang);
  const desc = tr(tour.description, tour.description_i18n, lang);

  const stepSections = tour.steps.map((step) => {
    const stepTitle = tr(step.title, step.title_i18n, lang) || `Step ${step.number}`;
    const stepContent = tr(step.content, step.content_i18n, lang);
    const file = shotFile(step.number, total);
    const shotPath = path.join(dir, file);
    const dataUri = embedImage(shotPath);

    const imgHtml = dataUri
      ? `<img class="t2p-shot" src="${dataUri}" alt="${escapeHtml(stepTitle)}" />`
      : `<p class="t2p-missing"><em>Screenshot pending — run the pipeline again to capture it.</em></p>`;

    let hintHtml = "";
    if (step.validation_type && step.validation_type !== "none") {
      const vmsg =
        tr(step.validation_message, step.validation_message_i18n, lang) ||
        VALIDATION_HINT[step.validation_type] ||
        "";
      if (vmsg) hintHtml = `<p class="t2p-hint">ℹ️ ${escapeHtml(vmsg)}</p>`;
    }

    return `  <section class="t2p-step">
    <h2>${step.number}. ${escapeHtml(stepTitle)}</h2>
${stepContent ? `    <p>${escapeHtml(stepContent)}</p>\n` : ""}${hintHtml ? `    ${hintHtml}\n` : ""}    ${imgHtml}
  </section>`;
  });

  return `<!DOCTYPE html>
<html lang="${lang.replace("_", "-")}">
<head>
<meta charset="UTF-8" />
<title>${escapeHtml(title)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color: #1f2328; max-width: 820px; margin: 0 auto; padding: 32px 24px; line-height: 1.55; }
  h1 { font-size: 1.6rem; margin: 0 0 4px; }
  .t2p-meta { color: #6b7280; font-size: 0.85rem; margin-bottom: 20px; }
  .t2p-desc { margin-bottom: 24px; }
  .t2p-step { margin-bottom: 32px; padding-bottom: 24px; border-bottom: 1px solid #e5e7eb; }
  .t2p-step h2 { font-size: 1.15rem; margin: 0 0 8px; }
  .t2p-shot { max-width: 100%; border: 1px solid #d0d7de; border-radius: 6px; margin-top: 10px; }
  .t2p-hint { background: #fff8e1; border: 1px solid #f5d76e; border-radius: 6px; padding: 8px 12px; font-size: 0.9rem; }
  .t2p-missing { color: #9ca3af; font-style: italic; }
  .t2p-footer { color: #9ca3af; font-size: 0.8rem; margin-top: 32px; }
</style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <div class="t2p-meta">User manual · ${escapeHtml(langName(lang))} · ${total} step${total === 1 ? "" : "s"}</div>
${desc ? `  <div class="t2p-desc">${escapeHtml(desc)}</div>\n` : ""}${stepSections.join("\n")}
  <div class="t2p-footer">Generated by tour2playwright from a Tour Recorder export.</div>
</body>
</html>
`;
}

/**
 * @param {object} tour normalized tour
 * @returns {Array<{filename:string, content:string, lang:string}>}
 */
export function genManuals(tour) {
  const total = tour.steps.length;
  return tour.langs.map((lang) => ({
    lang,
    filename: `${tour.slug}.${lang}.html`,
    content: genHtml(tour, lang, total),
  }));
}
