// Generate a Playwright .spec.ts for one tour, written directly into the
// target module's own tests/02-business/ folder.
//
// The spec navigates to the Odoo backend, then walks each step: locate the
// trigger, wait for it, screenshot the state the user acts on (with the target
// outlined), then perform the mapped action. Screenshots feed the manuals.
//
// The generated spec imports from this repo's shared fixtures (not
// `@playwright/test` directly) and carries `@module:<domain> @step:business
// @e2e` tags, so it's a normal citizen of the framework: it shows up in
// `npm test`, the master report, and passes `/review-tests` like any other
// spec. It executes via the MAIN suite's own runner/auth (not a separate
// login flow), so SHOT_DIR is a repo-root-relative path.
import { selectorToLocator, actionFor, jsString } from "./translate.mjs";
import { shotFile, shotDirFromRepoRoot } from "./names.mjs";

const START_PATH = process.env.ODOO_START_PATH || "/web";

/**
 * @param {object} tour normalized tour (from loadTours)
 * @param {string} domain target module (e.g. "hr")
 * @returns {{ filename: string, source: string, todos: Array<{step:number,msg:string}> }}
 */
export function genSpec(tour, domain) {
  const total = tour.steps.length;
  const dir = shotDirFromRepoRoot(tour.slug);
  const allTodos = [];
  const lines = [];

  lines.push(`// AUTO-GENERATED by tour2playwright from a Tour Recorder export.`);
  lines.push(`// Source tour: ${tour.name}`);
  lines.push(`// Regenerate with:  npm run gen -- ${domain} <export.json>  (from tools/tour2playwright/)`);
  lines.push(`// Review any "TODO" markers below — Odoo tour selectors/actions`);
  lines.push(`// don't all map 1:1 onto Playwright.`);
  lines.push(`import { test, expect } from "../../../../core/fixtures/index";`);
  lines.push(`import type { Page, Locator } from "@playwright/test";`);
  lines.push(`import fs from "node:fs";`);
  lines.push(``);
  lines.push(`const SHOT_DIR = ${jsString(dir)};`);
  lines.push(``);
  lines.push(`// Screenshot the current page with the target element outlined.`);
  lines.push(`async function shot(page: Page, loc: Locator, file: string) {`);
  lines.push(`  try {`);
  lines.push(`    await loc.scrollIntoViewIfNeeded({ timeout: 5000 });`);
  lines.push(`    await loc.evaluate((el) => el.setAttribute("data-t2p", "1"));`);
  lines.push(`    await page.addStyleTag({`);
  lines.push(`      content: '[data-t2p="1"]{outline:3px solid #e01e5a !important;outline-offset:2px !important;}',`);
  lines.push(`    });`);
  lines.push(`  } catch {}`);
  lines.push(`  fs.mkdirSync(SHOT_DIR, { recursive: true });`);
  lines.push(`  await page.screenshot({ path: \`\${SHOT_DIR}/\${file}\` });`);
  lines.push(`  try { await loc.evaluate((el) => el.removeAttribute("data-t2p")); } catch {}`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`test.describe(${jsString(`${tour.name} @module:${domain} @step:business @e2e`)}, () => {`);
  lines.push(`  test(${jsString(tour.name)}, async ({ page }) => {`);
  lines.push(`    await page.goto(${jsString(START_PATH)});`);
  lines.push(`    // Odoo keeps persistent long-polling/websocket connections open for`);
  lines.push(`    // real-time notifications, so "networkidle" never naturally resolves —`);
  lines.push(`    // bound it explicitly or it silently eats the whole test timeout as its`);
  lines.push(`    // fallback ceiling before its own .catch() ever fires.`);
  lines.push(`    await page.waitForLoadState("networkidle", { timeout: 10_000 }).catch(() => {});`);
  lines.push(``);

  for (const step of tour.steps) {
    const { expr, todos: selTodos } = selectorToLocator(step.trigger);
    const { code, todos: actTodos } = actionFor(expr, step);
    const file = shotFile(step.number, total);
    const label = `${String(step.number).padStart(2, "0")}. ${step.title || step.trigger || "step"}`;

    for (const t of [...selTodos, ...actTodos]) {
      allTodos.push({ step: step.number, msg: t });
    }

    // Indent multi-line action code (the "manual" case spans two lines).
    const actionCode = code
      .split("\n")
      .map((l) => `      ${l}`)
      .join("\n");

    lines.push(`    await test.step(${jsString(label)}, async () => {`);
    for (const t of [...selTodos, ...actTodos]) {
      lines.push(`      // TODO: ${t}`);
    }
    // `.first()` guards against Odoo selectors that match several nodes
    // (Playwright's strict mode would otherwise throw).
    // Timeout is generous (45s, not Playwright's usual default) because
    // staging/dev Odoo.sh databases can be slow to wake from idle on the
    // first real request — the element itself is often correct, it just
    // hasn't finished rendering yet.
    lines.push(`      const loc = (${expr}).first();`);
    lines.push(`      await loc.waitFor({ state: "visible", timeout: 45000 });`);
    lines.push(`      await shot(page, loc, ${jsString(file)});`);
    lines.push(actionCode);
    lines.push(`    });`);
    lines.push(``);
  }

  lines.push(`  });`);
  lines.push(`});`);
  lines.push(``);

  return {
    filename: `${domain}.${tour.slug}-tour.spec.ts`,
    source: lines.join("\n"),
    todos: allTodos,
  };
}
